version: "3.9"

services:
  backend:
    env_file:
      - .env
    # image: django
    build: backend/.
    # command: python -m gunicorn --bind :8000 backend.wsgi:application
    # command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  # migration:
  #   image: django
  #   env_file:
  #     - backend/.env
  #   command: python manage.py migrate --noinput # && python manage.py collectstatic --noinput
  #   volumes:
  #     - ./backend:/app:z
  #   depends_on:
  #     - db

  frontend:
    depends_on:
      - backend
    build: frontend/.
    expose:
      - 3000

  db:
    restart: unless-stopped
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
